<PISI>
    <Source>
        <Name>python-zope.exceptions</Name>
        <Homepage>https://zopeexceptions.readthedocs.io/</Homepage>
        <Packager>
            <Name>Joey Riches</Name>
            <Email>josephriches@gmail.com</Email>
        </Packager>
        <License>ZPL-2.1</License>
        <PartOf>programming.python</PartOf>
        <Summary xml:lang="en">Zope exceptions and implementations which are general purpose.</Summary>
        <Description xml:lang="en">Zope exceptions and implementations which are general purpose.
</Description>
        <Archive type="binary" sha1sum="79eb0752a961b8e0d15c77d298c97498fbc89c5a">https://sources.getsol.us/README.Solus</Archive>
    </Source>
    <Package>
        <Name>python-zope.exceptions</Name>
        <Summary xml:lang="en">Zope exceptions and implementations which are general purpose.</Summary>
        <Description xml:lang="en">Zope exceptions and implementations which are general purpose.
</Description>
        <PartOf>programming.python</PartOf>
        <Files>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope.exceptions-5.2-py3.12-nspkg.pth</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__init__.py</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/__init__.cpython-312.opt-1.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/__init__.cpython-312.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-312.opt-1.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-312.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/interfaces.cpython-312.opt-1.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/interfaces.cpython-312.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/log.cpython-312.opt-1.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/log.cpython-312.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/exceptionformatter.py</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/interfaces.py</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/log.py</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__init__.py</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/__init__.cpython-312.opt-1.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/__init__.cpython-312.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-312.opt-1.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-312.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_log.cpython-312.opt-1.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_log.cpython-312.pyc</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/test_exceptionformatter.py</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope/exceptions/tests/test_log.py</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope_exceptions-5.2.dist-info/LICENSE.txt</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope_exceptions-5.2.dist-info/METADATA</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope_exceptions-5.2.dist-info/RECORD</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope_exceptions-5.2.dist-info/WHEEL</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope_exceptions-5.2.dist-info/namespace_packages.txt</Path>
            <Path fileType="library">/usr/lib/python3.12/site-packages/zope_exceptions-5.2.dist-info/top_level.txt</Path>
        </Files>
    </Package>
    <History>
        <Update release="2">
            <Date>2025-05-17</Date>
            <Version>5.2</Version>
            <Comment>Packaging update</Comment>
            <Name>Joey Riches</Name>
            <Email>josephriches@gmail.com</Email>
        </Update>
    </History>
</PISI>